services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ../..:/workspaces
      - /var/run/docker.sock:/var/run/docker.sock
      - claude-data:/home/vscode/.claude
    command: ["sleep", "infinity"]

volumes:
  claude-data:
